### ISSUE TITLE
AttributeError: 'str' object has no attribute 'string'

### ISSUE THREAD

**Issue by reinalin** [FXTD-ODYSSEY/pyuiw#2]
python 3.7.8 
File "c:\python37\lib\site-packages\pyuiw\uic\uiparser.py", line 244, in createWidget
    bg_name = bg_i18n.string
bg_i18n返回是str

**Comment by FXTD-ODYSSEY** [comment]
请问你是怎么触发这个报错的

**Comment by reinalin** [comment]
"C:\Python37\Scripts\pyuiw.exe" -d -ni -w "createMain_dy.ui"

[createMain_dy.ui](https://drive.google.com/file/d/1nVpscVu_MHXLIHF9h7X2fe3-NpIIyEhB/view?usp=sharing)

**Comment by FXTD-ODYSSEY** [comment]
这个问题是你的 ui 文件的问题
![image](https://user-images.githubusercontent.com/40897360/177238940-2c5e6c73-2f56-411d-84f3-883d1e1e4e64.png)

把这个非法的 `buttongroup` 删除，然后打开 designer 重新保存一下 ui 文件就可以了。
